const CLASSIC_COLORS = [
  { slug: "white", name: "White", hex: "#FFFFFF" },
  { slug: "black", name: "Black", hex: "#141414" },
  { slug: "sport-grey", name: "Sport Grey", hex: "#B4B4B6" },
  { slug: "navy", name: "Navy", hex: "#1F2A44" },
  { slug: "royal", name: "Royal", hex: "#1E4B9E" },
  { slug: "red", name: "Red", hex: "#C8102E" },
  { slug: "forest", name: "Forest", hex: "#1F3D2B" },
  { slug: "sand", name: "Sand", hex: "#D6C7AE" },
];

const ADULT_SIZES = [
  { label: "S", surcharge: 0 },
  { label: "M", surcharge: 0 },
  { label: "L", surcharge: 0 },
  { label: "XL", surcharge: 0 },
  { label: "2XL", surcharge: 3 },
  { label: "3XL", surcharge: 5 },
];

const ONE_SIZE = [{ label: "OS", surcharge: 0 }];
const BREAKS = [
  { min_qty: 1, off: 0 },
  { min_qty: 6, off: -1 },
  { min_qty: 12, off: -1.75 },
  { min_qty: 24, off: -2.5 },
  { min_qty: 50, off: -3.5 },
];

export const additionalCategories = [
  {
    slug: "sweatshirts",
    name: "Sweatshirts",
    description: "Fleece layers built for bold, durable custom prints.",
    sort: 2,
  },
  {
    slug: "accessories",
    name: "Accessories",
    description: "Caps, totes and mugs that carry your brand beyond the tee.",
    sort: 3,
  },
];

export const additionalProducts = [
  {
    slug: "premium-pullover-hoodie",
    name: "Premium Pullover Hoodie",
    style: "KCP-H100",
    category: "sweatshirts",
    kind: "hoodie",
    material: "80/20 cotton-poly fleece, 8.0 oz, unisex fit",
    blurb: "A substantial fleece hoodie with a smooth face for crisp front and back prints.",
    description:
      "A dependable everyday hoodie with a lined hood, ribbed cuffs and a roomy kangaroo pocket. The smooth face keeps large artwork clean while the fleece interior stays comfortable for daily wear.",
    base_price: 28,
    compare_at: null,
    print_fee: 6,
    print_area: { frontW: 0.46, frontH: 0.42, backW: 0.58, backH: 0.58 },
    featured: true,
    sort: 15,
    colors: CLASSIC_COLORS,
    sizes: ADULT_SIZES,
    breaks: BREAKS,
    images: [{ url: "/img/mockups/families/hoodie/BLK_fr.webp", alt: "Premium Pullover Hoodie in Black" }],
  },
  {
    slug: "heavyweight-crewneck",
    name: "Heavyweight Crewneck",
    style: "KCP-C100",
    category: "sweatshirts",
    kind: "crew",
    material: "80/20 cotton-poly fleece, 8.0 oz, unisex fit",
    blurb: "A clean crewneck silhouette with a wide, reliable print surface.",
    description:
      "The no-hood layer for uniforms, campus groups and retail collections. Ribbed trim holds its shape while the substantial fleece body gives artwork a stable, premium surface.",
    base_price: 24,
    compare_at: null,
    print_fee: 6,
    print_area: { frontW: 0.46, frontH: 0.44, backW: 0.58, backH: 0.6 },
    featured: true,
    sort: 16,
    colors: CLASSIC_COLORS,
    sizes: ADULT_SIZES,
    breaks: BREAKS,
    images: [{ url: "/img/mockups/families/crew/BLK_fr.webp", alt: "Heavyweight Crewneck in Black" }],
  },
  {
    slug: "five-panel-cap",
    name: "Five-Panel Cap",
    style: "KCP-CAP1",
    category: "accessories",
    kind: "cap",
    material: "Cotton twill, five-panel construction, adjustable strap",
    blurb: "A structured front panel for compact marks, team identities and small artwork.",
    description:
      "A clean five-panel cap with a curved brim and adjustable back strap. The front panel keeps small logos and wordmarks visible without overwhelming the silhouette.",
    base_price: 16,
    compare_at: null,
    print_fee: 4,
    print_area: { frontW: 0.58, frontH: 0.3, backW: 0.5, backH: 0.22 },
    featured: false,
    sort: 17,
    colors: CLASSIC_COLORS.slice(0, 6),
    sizes: ONE_SIZE,
    breaks: BREAKS,
    images: [{ url: "/img/mockups/families/cap/BLK_fr.webp", alt: "Five-Panel Cap in Black" }],
  },
  {
    slug: "canvas-tote",
    name: "Canvas Tote",
    style: "KCP-TOTE1",
    category: "accessories",
    kind: "tote",
    material: "12 oz cotton canvas, reinforced handles",
    blurb: "A sturdy reusable tote with room for bold front artwork and event marks.",
    description:
      "A practical canvas carryall for markets, events and everyday brand visibility. The broad front panel gives artwork plenty of breathing room and the reinforced handles are built for repeat use.",
    base_price: 14,
    compare_at: null,
    print_fee: 4,
    print_area: { frontW: 0.52, frontH: 0.58, backW: 0.52, backH: 0.58 },
    featured: false,
    sort: 18,
    colors: [
      { slug: "natural", name: "Natural", hex: "#F2E7D2" },
      { slug: "black", name: "Black", hex: "#141414" },
      { slug: "navy", name: "Navy", hex: "#1F2A44" },
    ],
    sizes: ONE_SIZE,
    breaks: BREAKS,
    images: [{ url: "/img/mockups/families/tote/NATL_fr.webp", alt: "Canvas Tote in Natural" }],
  },
  {
    slug: "ceramic-mug",
    name: "Ceramic Mug",
    style: "KCP-MUG1",
    category: "accessories",
    kind: "mug",
    material: "11 oz glossy ceramic, dishwasher-safe finish",
    blurb: "A classic ceramic mug for logos, team marks and small-run gifts.",
    description:
      "A dependable 11 oz ceramic mug with a smooth printable panel and a comfortable handle. A simple way to carry a brand into offices, studios and customer gift packs.",
    base_price: 12,
    compare_at: null,
    print_fee: 4,
    print_area: { frontW: 0.6, frontH: 0.42, backW: 0.6, backH: 0.42 },
    featured: false,
    sort: 19,
    colors: [
      { slug: "white", name: "White", hex: "#FFFFFF" },
      { slug: "black", name: "Black", hex: "#141414" },
      { slug: "red", name: "Red", hex: "#C8102E" },
    ],
    sizes: ONE_SIZE,
    breaks: BREAKS,
    images: [{ url: "/img/mockups/families/mug/WHT_fr.webp", alt: "Ceramic Mug in White" }],
  },
];
